### ISSUE TITLE
Maximum recursion exceeded in `authorizeCreate` called in `createIdentifier`

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#346] opened 2022-10-04 18:45 UTC
```
The following error occurred.  Notifications of any additional occurrences of this error will be suppressed for the next 1:00:00.

Exception raised in encoder.iterencode:
RecursionError: maximum recursion depth exceeded in comparison

Traceback (most recent call last):
  File "/ezid/ezid/impl/ezid.py", line 259, in createIdentifier
    if not impl.policy.authorizeCreate(user, normalizedIdentifier):
  File "/ezid/ezid/impl/policy.py", line 47, in authorizeCreate
    if any(authorizeCreate(u, prefix) for u in user.proxy_for.all()):
  File "/ezid/ezid/impl/policy.py", line 47, in <genexpr>
    if any(authorizeCreate(u, prefix) for u in user.proxy_for.all()):
...
File "/ezid/ezid/impl/policy.py", line 40, in authorizeCreate
    logger.debug(f'Checking if user can create identifier. user="{user}" prefix="{prefix}"')
  File "/ezid/.pyenv/versions/3.8.5/lib/python3.8/logging/__init__.py", line 1422, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/ezid/.pyenv/versions/3.8.5/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/ezid/.pyenv/versions/3.8.5/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/ezid/.pyenv/versions/3.8.5/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/ezid/.pyenv/versions/3.8.5/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/ezid/.pyenv/versions/3.8.5/lib/python3.8/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/ezid/.pyenv/versions/3.8.5/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/ezid/.pyenv/versions/3.8.5/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/ecs_logging-1.1.0-py3.8.egg/ecs_logging/_stdlib.py", line 166, in format
    return json_dumps(result)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/ecs_logging-1.1.0-py3.8.egg/ecs_logging/_utils.py", line 177, in json_dumps
    json_dumps(value)[1:],
  File "/ezid/.pyenv/versions/3.8.5/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/ezid/.pyenv/versions/3.8.5/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/ezid/.pyenv/versions/3.8.5/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
RecursionError: maximum recursion depth exceeded in comparison
```
```

**Comment by mariagould** [comment] 2023-03-07 19:21
Unable to reproduce and not seeing repeat instances. Closing for now.

**Closed by mariagould** 2023-03-07 19:21 UTC
Labels: bug, priority-normal
