### ISSUE TITLE
list index out of range error editing DOI

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#370] opened 2022-12-17 00:02 UTC
```
Internal Server Error: /manage/edit/doi:10.5072/FK2445T115

IndexError at /manage/edit/doi:10.5072/FK2445T115
list index out of range

Request Method: POST
Request URL: http://ezid.cdlib.org/manage/edit/doi:10.5072/FK2445T115
Django Version: 3.2.7
Python Executable: /ezid/.pyenv/versions/ezid-py3/bin/python
Python Version: 3.8.5
...
Traceback (most recent call last):
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/ezid/ezid/impl/ui_manage.py", line 253, in edit
    d = impl.ui_create.validate_adv_form_datacite_xml(request, d)
  File "/ezid/ezid/impl/ui_create.py", line 273, in validate_adv_form_datacite_xml
    d['form'] = impl.form_objects.getIdForm_datacite_xml(None, request)
  File "/ezid/ezid/impl/form_objects.py", line 1076, in getIdForm_datacite_xml
    creator_set = CreatorSet(
  File "/ezid/ezid/impl/form_objects.py", line 470, in __init__
    self.forms[0].empty_permitted = False

Exception Type: IndexError at /manage/edit/doi:10.5072/FK2445T115
Exception Value: list index out of range
Request information:
USER: AnonymousUser

GET: No GET data

POST:
action = 'edit'
identifier = 'doi:10.5072/FK2445T115'
original_profile = 'datacite'
simpleToAdvanced = 'True'
target = 'http://escholarship.org/uc/item/02d8n4s2'
datacite.creator = 'Shenoy, Ajay, Laura V. Zimmermann'
datacite.title = 'Political Organizations and Political Scope'
datacite.publisher = 'CEGA Working Paper Series No. WPS-214. Center for Effective Global Action. University of California, Berkeley'
datacite.publicationyear = '2022'
datacite.resourcetype = 'Text'
_status = 'public'
stat_reason = ''
_export = 'yes'

FILES: No FILES data

...

PATH_INFO = '/manage/edit/doi:10.5072/FK2445T115'
PATH_TRANSLATED = '/ezid/ezid/apache/django.wsgi/manage/edit/doi:10.5072/FK2445T115'
QUERY_STRING = ''

```

**Comment by datadavev** [comment] 2022-12-21 19:11
Unable to reproduce and have not seen further occurrences. Dropping priority.

**Comment by rushirajnenuji** [comment] 2023-01-31 19:45
Closing out this issue; cannot reproduce.

**Closed by rushirajnenuji** 2023-01-31 19:45 UTC
Labels: bug, priority-low
