### ISSUE TITLE
EZID allows minting test identifier with credentials, but modifying fails

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/ezid#426] opened 2023-05-26 18:23 UTC
We are using a Ruby EZID client (ezid-client https://rubygems.org/gems/ezid-client/versions/ ).

Minting works with our credentials:
```
ezid_response = ezid_client.mint_identifier(shoulder, status: 'reserved', profile: 'datacite')
# gives 201--created
# gives "success: doi:10.5072/FK2BZ6BB3V | ark:/b5072/fk2bz6bb3v"
```

5 minutes later, updating metadata fails.
```
ezid_client.modify_identifier(resource.identifier_str, **params)
# gives Net::HTTPServerException (403 Forbidden)
```

In the past until somewhat recently this worked and we were able to modify the identifier metadata for an identifier we'd minted/reserved.  The library passes along that this is a 403 from EZID.

shoulder: "doi:10.5072/FK2" and user is `dash`.

I'm not sure this is simply an account problem since wouldn't the minting fail, also?

Not a high priority item since we only run into problems with test identifiers for our dev/stage systems.

**Comment by mariagould** [comment] 2023-05-30 18:00
Hi @sfisher thanks for reporting this. Can you clarify what type of update you were trying to make? And are you able to reproduce the error on your end?

**Comment by sfisher** [comment] 2023-05-30 18:39
It's very reproducible since it happens every time.  I'll have to try digging through code to see if I can get headers/body from the EZID client library.

**Comment by rushirajnenuji** [comment] 2023-05-31 20:27
Hey @sfisher ,

I checked our ALB WAF logs on Open search, and our initial theory was right. One of the ALB WAF rule is blocking the request for the DOI mentioned in the ticket. The initial mint operation is going through because it does not have any request body, and the subsequent update operation is failing because AWS suspects that some part of the request body is trying to get the EC2 metadata. 

The rule blocking the request is:
```json
{
  "ruleGroupId": "AWS#AWSManagedRulesCommonRuleSet",
  "terminatingRule": {
    "ruleId": "EC2MetaDataSSRF_BODY",
    "action": "BLOCK",
    "overriddenAction": "BLOCK",
    "ruleMatchDetails": null
  },
  "nonTerminatingMatchingRules": [],
  "excludedRules": null,
  "customerConfig": null
}
```

We had a similar issue with `sb-nceas` user, where we had a test that was trying to set the `_target` URL to `localhost`  and the request was being blocked by the same rule/ruleID.

Please let me know if a snapshot of the entire ALB WAF object would be helpful, or if any additional steps are required on our end.

**Comment by sfisher** [comment] 2023-05-31 21:04
Thanks @rushirajnenuji,

Thanks for figuring this out.  We don't really need to update identifiers from local development machines and I can see how the localhost URL might be problematic.

I originally saw some failures and didn't really understand why at first.  Since we know what's going on, we can just test any of this functionality from our development environment when we need to.  I don't think you need to modify this rule for us now that we're aware.

I hope this didn't take too much of your time to figure out.

Thanks for your help.

**Comment by mariagould** [comment] 2023-06-27 18:41
This should be resolved with our adjustments to the new EZID WAF rules. Closing for now but please ping us @sfisher if you see this come up again!

**Closed by mariagould** 2023-06-27 18:41 UTC
Labels: bug
