### ISSUE TITLE
Login returns wrong response with false credentials

### ISSUE THREAD

**Issue by rushirajnenuji** [CDLUC3/ezid#210] opened 2022-02-02 19:01 UTC
When we try to login with false credentials, we get a 500 error instead of 401 unauthorized

- expected: 401 unauthorized (current behavior on stage/prod)
```bash
MacBook-Pro:tools nenuji$ python client s py3testuser1:password1 login
401 Unauthorized
error: unauthorized
```
- current: 500 Internal Server Error
```bash
500 Internal Server Error
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="robots" content="NONE,NOARCHIVE">
  <title>DoesNotExist
          at /login</title>
          ....
```

**Comment by rogerdahl** [comment] 2022-02-16 18:24
Cannot reproduce on local ezid-py3. Will retry after deploy to stg-py3.

**Comment by rogerdahl** [comment] 2022-02-16 23:27
Appears to be fixed on stg-py3.

**Closed** 2022-03-01 19:25 UTC
Labels: bug, python 3
